rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3

before_script: "./spec/ci/before_script"

script: "./spec/ci/script"

env:
  - RADIANT_VERSION=1.0.1 DB=mysql
  - RADIANT_VERSION=1.0.1 DB=postgres

notifications:
  recipients:
    - johnmuhl@gmail.com
  irc: "irc.freenode.org#radiantcms"
